 ' Generated by SOLAR Generation Studio .
 ' Plugin Version: 1.0.0.0
Imports System.Collections.Generic
Imports System.Configuration
Imports System.Data
Imports System.Data.SqlClient
Imports Solar.DataHelper

Namespace Views
End Namespace 'Views
