
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class Archivos_Paciente
{

    public int archivo_id { get; set; }

    public string nombreArchivo { get; set; }

    public Nullable<int> paciente_id { get; set; }

    public Nullable<System.DateTime> fecha_carga { get; set; }

    public Nullable<int> usuario_carga { get; set; }

    public byte[] archivo { get; set; }

    public string observacion { get; set; }

    public Nullable<int> tipo_archivo_id { get; set; }



    public virtual TBL_Usuarios TBL_Usuarios { get; set; }

    public virtual Tipo_Archivo Tipo_Archivo { get; set; }

    public virtual Pacientes Pacientes { get; set; }

}

}
