
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class ContactoPaciente
{

    public int contacto_id { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }

    public string tel1 { get; set; }

    public string tel2 { get; set; }

    public string tel3 { get; set; }

    public string relacion { get; set; }

    public Nullable<int> paciente_id { get; set; }

}

}
