//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_LaboratorioCab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EST_LaboratorioCab()
        {
            this.EST_LaboratorioItems = new HashSet<EST_LaboratorioItems>();
        }
    
        public int id_solicitud { get; set; }
        public Nullable<int> paciente_id { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public Nullable<int> tipo { get; set; }
        public string otrosEstudios { get; set; }
        public string observacionesMed { get; set; }
        public string observacionesBioq { get; set; }
        public Nullable<int> estado_id { get; set; }
        public Nullable<int> usuario_id { get; set; }
    
        public virtual EST_LaboratorioEstados EST_LaboratorioEstados { get; set; }
        public virtual EST_LaboratorioTipos EST_LaboratorioTipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_LaboratorioItems> EST_LaboratorioItems { get; set; }
    }
}
