
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class Habitaciones
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Habitaciones()
    {

        this.PacientesTesting = new HashSet<PacientesTesting>();

        this.Pacientes = new HashSet<Pacientes>();

    }


    public int habitacion_id { get; set; }

    public string descripcion { get; set; }

    public Nullable<int> piso_id { get; set; }

    public int sede_id { get; set; }

    public Nullable<int> baja { get; set; }



    public virtual Sedes Sedes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PacientesTesting> PacientesTesting { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pacientes> Pacientes { get; set; }

}

}
