
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class HC
{

    public int HC_id { get; set; }

    public Nullable<int> paciente_id { get; set; }

    public string tipo { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

    public Nullable<int> usuario_id { get; set; }

    public string texto { get; set; }

}

}
