//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MED_Solicita_Medicamento_Nuevo
    {
        public int medicamento_id { get; set; }
        public string bejerman_id { get; set; }
        public string medicamento { get; set; }
        public Nullable<int> presentacion_id { get; set; }
        public Nullable<int> unidadDeMedida_id { get; set; }
        public Nullable<bool> autoriza { get; set; }
        public Nullable<bool> suministraCompra { get; set; }
        public Nullable<int> usuarioSolicita_id { get; set; }
        public Nullable<System.DateTime> fechaSolicita { get; set; }
        public Nullable<int> usuarioAutoriza_id { get; set; }
        public Nullable<System.DateTime> fechaAutoriza { get; set; }
        public Nullable<bool> pendiente { get; set; }
        public Nullable<bool> bejermanAlta { get; set; }
        public Nullable<bool> inactivo { get; set; }
        public string Potencia { get; set; }
        public Nullable<int> paciente_id { get; set; }
        public Nullable<System.DateTime> fechaHasta { get; set; }
        public Nullable<System.DateTime> fechaDesde { get; set; }
    
        public virtual MED_Presentacion MED_Presentacion { get; set; }
        public virtual MED_UnidadDeMedida MED_UnidadDeMedida { get; set; }
        public virtual TBL_Usuarios TBL_Usuarios { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
