
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class MED_Presentacion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MED_Presentacion()
    {

        this.MED_Solicita_Medicamento_Nuevo = new HashSet<MED_Solicita_Medicamento_Nuevo>();

    }


    public int presentacion_id { get; set; }

    public string descripcion { get; set; }

    public Nullable<int> unidadDeMedida_id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MED_Solicita_Medicamento_Nuevo> MED_Solicita_Medicamento_Nuevo { get; set; }

}

}
