//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MED_Medicamento_Via
    {
        public int medicamentoVia_id { get; set; }
        public string medicamento_id { get; set; }
        public int via_id { get; set; }
    
        public virtual MED_Via MED_Via { get; set; }
        public virtual MEDICAMENTO MEDICAMENTO { get; set; }
    }
}
