//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MED_OtraPonderacionPuntaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MED_OtraPonderacionPuntaje()
        {
            this.MED_PuntajeAdicionalListaEspera = new HashSet<MED_PuntajeAdicionalListaEspera>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public decimal puntaje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MED_PuntajeAdicionalListaEspera> MED_PuntajeAdicionalListaEspera { get; set; }
    }
}
