
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class MED_PacienteModulo
{

    public int id { get; set; }

    public int paciente_id { get; set; }

    public string modulo_id { get; set; }

    public Nullable<System.DateTime> fechaAlta { get; set; }

    public Nullable<System.DateTime> fechaBaja { get; set; }



    public virtual MED_Modulo MED_Modulo { get; set; }

    public virtual Pacientes Pacientes { get; set; }

}

}
