
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class MED_ModuloEmpresa
{

    public int Id { get; set; }

    public string codEmp { get; set; }

    public string obraSocial_id { get; set; }

    public string modulo_id { get; set; }

    public double costo { get; set; }

    public System.DateTime fechaVigencia { get; set; }

    public System.DateTime fechaAlta { get; set; }



    public virtual MED_Modulo MED_Modulo { get; set; }

}

}
