//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoEgreso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MotivoEgreso()
        {
            this.MED_ListaEspera = new HashSet<MED_ListaEspera>();
        }
    
        public int motivoEgreso_id { get; set; }
        public string Descripcion { get; set; }
        public int tipo_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MED_ListaEspera> MED_ListaEspera { get; set; }
        public virtual MED_TipoEgreso MED_TipoEgreso { get; set; }
    }
}
