//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes_Historial
    {
        public int paciente_id { get; set; }
        public Nullable<int> numeroHistoriaClinica { get; set; }
        public Nullable<int> numeroInternacion { get; set; }
        public Nullable<int> habitacion_id { get; set; }
        public Nullable<int> sede_id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<bool> genero { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<int> tipoDocumento_id { get; set; }
        public Nullable<int> numeroDocumento { get; set; }
        public Nullable<int> diagnostico_id { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string obraSocial_id { get; set; }
        public string numeroObraSocial { get; set; }
        public Nullable<System.DateTime> fechaEgreso { get; set; }
        public Nullable<int> motivoEgreso_id { get; set; }
        public Nullable<bool> acompaniante { get; set; }
        public Nullable<bool> itemPendiente { get; set; }
        public Nullable<bool> preAlta { get; set; }
        public Nullable<bool> solicitudEstudio { get; set; }
        public Nullable<bool> solicitudTraslado { get; set; }
        public Nullable<bool> interconsultaPendiente { get; set; }
        public Nullable<bool> altaAutorizada { get; set; }
        public Nullable<int> HS_08 { get; set; }
        public Nullable<int> HS_09 { get; set; }
        public Nullable<int> HS_10 { get; set; }
        public Nullable<int> HS_11 { get; set; }
        public Nullable<int> HS_12 { get; set; }
        public Nullable<int> HS_13 { get; set; }
        public Nullable<int> HS_14 { get; set; }
        public Nullable<int> HS_15 { get; set; }
        public Nullable<int> HS_16 { get; set; }
        public Nullable<int> HS_17 { get; set; }
        public Nullable<int> HS_18 { get; set; }
        public Nullable<int> HS_19 { get; set; }
        public Nullable<int> HS_20 { get; set; }
        public Nullable<int> HS_21 { get; set; }
        public Nullable<int> HS_22 { get; set; }
        public Nullable<int> HS_23 { get; set; }
        public Nullable<int> HS_24 { get; set; }
        public Nullable<int> HS_01 { get; set; }
        public Nullable<int> HS_02 { get; set; }
        public Nullable<int> HS_03 { get; set; }
        public Nullable<int> HS_04 { get; set; }
        public Nullable<int> HS_05 { get; set; }
        public Nullable<int> HS_06 { get; set; }
        public Nullable<int> HS_07 { get; set; }
        public Nullable<int> HS_SH { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<bool> respira { get; set; }
        public Nullable<bool> contacto { get; set; }
        public Nullable<bool> tqt { get; set; }
        public Nullable<bool> arm { get; set; }
        public Nullable<bool> oxigeno { get; set; }
        public Nullable<bool> vo { get; set; }
        public Nullable<bool> sng { get; set; }
        public Nullable<bool> gastro { get; set; }
        public Nullable<bool> sv { get; set; }
        public Nullable<bool> cat { get; set; }
        public Nullable<bool> talla { get; set; }
        public Nullable<bool> talon { get; set; }
        public Nullable<bool> sac { get; set; }
        public Nullable<bool> isq { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<bool> paciente_traumatico { get; set; }
        public string txtPacTraumatico { get; set; }
        public Nullable<bool> paciente_judicializado { get; set; }
        public string txtPacJudicializado { get; set; }
    }
}
