//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_Alimento_Paciente
    {
        public int id_paciente { get; set; }
        public int id_alimento { get; set; }
        public int id_horario_administracion { get; set; }
        public string observacion { get; set; }
    
        public virtual Pacientes Pacientes { get; set; }
        public virtual PRO_Alimento PRO_Alimento { get; set; }
        public virtual PRO_Alimento_Horarios_Administracion PRO_Alimento_Horarios_Administracion { get; set; }
    }
}
