//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_Cuidado_Oral
    {
        public int cuidadoOral_id { get; set; }
        public Nullable<int> paciente_id { get; set; }
        public Nullable<int> procedimiento_id { get; set; }
        public Nullable<bool> placaDescanso { get; set; }
        public Nullable<bool> mordillo { get; set; }
        public Nullable<bool> clorhexidina { get; set; }
        public Nullable<bool> HS_08 { get; set; }
        public Nullable<bool> HS_09 { get; set; }
        public Nullable<bool> HS_10 { get; set; }
        public Nullable<bool> HS_11 { get; set; }
        public Nullable<bool> HS_12 { get; set; }
        public Nullable<bool> HS_13 { get; set; }
        public Nullable<bool> HS_14 { get; set; }
        public Nullable<bool> HS_15 { get; set; }
        public Nullable<bool> HS_16 { get; set; }
        public Nullable<bool> HS_17 { get; set; }
        public Nullable<bool> HS_18 { get; set; }
        public Nullable<bool> HS_19 { get; set; }
        public Nullable<bool> HS_20 { get; set; }
        public Nullable<bool> HS_21 { get; set; }
        public Nullable<bool> HS_22 { get; set; }
        public Nullable<bool> HS_23 { get; set; }
        public Nullable<bool> HS_24 { get; set; }
        public Nullable<bool> HS_01 { get; set; }
        public Nullable<bool> HS_02 { get; set; }
        public Nullable<bool> HS_03 { get; set; }
        public Nullable<bool> HS_04 { get; set; }
        public Nullable<bool> HS_05 { get; set; }
        public Nullable<bool> HS_06 { get; set; }
        public Nullable<bool> HS_07 { get; set; }
        public string observacion { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<System.DateTime> fechaAltaSistema { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public string motivoBaja { get; set; }
    }
}
