//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Principal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_PHPV2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRO_PHPV2()
        {
            this.PRO_PHPV2_ADITIVO = new HashSet<PRO_PHPV2_ADITIVO>();
            this.PRO_SuministroDeProcedimiento_Historico = new HashSet<PRO_SuministroDeProcedimiento_Historico>();
            this.PRO_SuministroDeProcedimiento = new HashSet<PRO_SuministroDeProcedimiento>();
        }
    
        public int id_php { get; set; }
        public Nullable<int> tamanio_frasco { get; set; }
        public Nullable<bool> bic { get; set; }
        public Nullable<int> gotas_minuto { get; set; }
        public Nullable<int> ml_hora { get; set; }
        public Nullable<System.DateTime> fecha_carga { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
        public Nullable<int> usr_carga { get; set; }
        public Nullable<int> frasco1 { get; set; }
        public Nullable<int> frasco2 { get; set; }
        public Nullable<int> frasco3 { get; set; }
        public Nullable<int> frasco4 { get; set; }
        public Nullable<int> frasco5 { get; set; }
        public Nullable<int> frasco6 { get; set; }
        public Nullable<int> frasco7 { get; set; }
        public Nullable<int> frasco8 { get; set; }
        public Nullable<int> frasco9 { get; set; }
        public Nullable<int> frasco10 { get; set; }
        public string obs { get; set; }
    
        public virtual PRO_PHPV2_DILUYENTE PRO_PHPV2_DILUYENTE { get; set; }
        public virtual PRO_PHPV2_DILUYENTE PRO_PHPV2_DILUYENTE1 { get; set; }
        public virtual PRO_PHPV2_DILUYENTE PRO_PHPV2_DILUYENTE2 { get; set; }
        public virtual PRO_PHPV2_DILUYENTE PRO_PHPV2_DILUYENTE3 { get; set; }
        public virtual PRO_PHPV2_DILUYENTE PRO_PHPV2_DILUYENTE4 { get; set; }
        public virtual PRO_PHPV2_DILUYENTE PRO_PHPV2_DILUYENTE5 { get; set; }
        public virtual PRO_PHPV2_DILUYENTE PRO_PHPV2_DILUYENTE6 { get; set; }
        public virtual PRO_PHPV2_DILUYENTE PRO_PHPV2_DILUYENTE7 { get; set; }
        public virtual PRO_PHPV2_DILUYENTE PRO_PHPV2_DILUYENTE8 { get; set; }
        public virtual PRO_PHPV2_DILUYENTE PRO_PHPV2_DILUYENTE9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRO_PHPV2_ADITIVO> PRO_PHPV2_ADITIVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRO_SuministroDeProcedimiento_Historico> PRO_SuministroDeProcedimiento_Historico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRO_SuministroDeProcedimiento> PRO_SuministroDeProcedimiento { get; set; }
    }
}
