
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class PRO_Procedimiento
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PRO_Procedimiento()
    {

        this.PRO_Asociacion_Procedimiento = new HashSet<PRO_Asociacion_Procedimiento>();

        this.PRO_Asociacion_Procedimiento_Proc = new HashSet<PRO_Asociacion_Procedimiento_Proc>();

        this.PRO_Asociacion_Procedimiento_Proc1 = new HashSet<PRO_Asociacion_Procedimiento_Proc>();

        this.PRO_SuministroDeProcedimiento_Historico = new HashSet<PRO_SuministroDeProcedimiento_Historico>();

        this.PRO_SuministroDeProcedimiento = new HashSet<PRO_SuministroDeProcedimiento>();

    }


    public int procedimiento_id { get; set; }

    public string descripcion { get; set; }

    public Nullable<int> tipoProcedimiento_id { get; set; }

    public Nullable<bool> inactivo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_Asociacion_Procedimiento> PRO_Asociacion_Procedimiento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_Asociacion_Procedimiento_Proc> PRO_Asociacion_Procedimiento_Proc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_Asociacion_Procedimiento_Proc> PRO_Asociacion_Procedimiento_Proc1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_SuministroDeProcedimiento_Historico> PRO_SuministroDeProcedimiento_Historico { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_SuministroDeProcedimiento> PRO_SuministroDeProcedimiento { get; set; }

}

}
