
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class PRO_Historial_Php
{

    public int php_id { get; set; }

    public Nullable<int> paciente_id { get; set; }

    public Nullable<int> procedimiento_id { get; set; }

    public Nullable<bool> ml_100 { get; set; }

    public Nullable<bool> ml_250 { get; set; }

    public Nullable<bool> ml_500 { get; set; }

    public Nullable<bool> ml_1000 { get; set; }

    public Nullable<bool> bic { get; set; }

    public Nullable<int> gotaHora_id { get; set; }

    public Nullable<int> mlHora { get; set; }

    public Nullable<int> mlDia { get; set; }

    public Nullable<int> frascoUno_id { get; set; }

    public string aditivoUno_id { get; set; }

    public Nullable<int> frascoDos_id { get; set; }

    public string aditivoDos_id { get; set; }

    public Nullable<int> frascoTres_id { get; set; }

    public string aditivoTres_id { get; set; }

    public Nullable<int> frascoCuatro_id { get; set; }

    public string aditivoCuatro_id { get; set; }

    public Nullable<int> frascoCinco_id { get; set; }

    public string aditivoCinco_id { get; set; }

    public Nullable<int> frascoSeis_id { get; set; }

    public string aditivoSeis_id { get; set; }

    public Nullable<int> frascoSiete_id { get; set; }

    public string aditivoSiete_id { get; set; }

    public Nullable<int> frascoOcho_id { get; set; }

    public string aditivoOcho_id { get; set; }

    public Nullable<int> frascoNueve_id { get; set; }

    public string aditivoNueve_id { get; set; }

    public Nullable<int> frascoDiez_id { get; set; }

    public string aditivoDiez_id { get; set; }

    public string observacion { get; set; }

    public Nullable<int> usuario_id { get; set; }

    public Nullable<System.DateTime> fechaAltaSistema { get; set; }

    public Nullable<System.DateTime> fechaModificacion { get; set; }

    public Nullable<System.DateTime> fechaBaja { get; set; }

    public string motivoBaja { get; set; }

}

}
