
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class PRO_PHPV2_DILUYENTE
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PRO_PHPV2_DILUYENTE()
    {

        this.PRO_PHPV2 = new HashSet<PRO_PHPV2>();

        this.PRO_PHPV21 = new HashSet<PRO_PHPV2>();

        this.PRO_PHPV22 = new HashSet<PRO_PHPV2>();

        this.PRO_PHPV23 = new HashSet<PRO_PHPV2>();

        this.PRO_PHPV24 = new HashSet<PRO_PHPV2>();

        this.PRO_PHPV25 = new HashSet<PRO_PHPV2>();

        this.PRO_PHPV26 = new HashSet<PRO_PHPV2>();

        this.PRO_PHPV27 = new HashSet<PRO_PHPV2>();

        this.PRO_PHPV28 = new HashSet<PRO_PHPV2>();

        this.PRO_PHPV29 = new HashSet<PRO_PHPV2>();

    }


    public int id_diluyente { get; set; }

    public string descripcion_diluyente { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_PHPV2> PRO_PHPV2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_PHPV2> PRO_PHPV21 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_PHPV2> PRO_PHPV22 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_PHPV2> PRO_PHPV23 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_PHPV2> PRO_PHPV24 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_PHPV2> PRO_PHPV25 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_PHPV2> PRO_PHPV26 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_PHPV2> PRO_PHPV27 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_PHPV2> PRO_PHPV28 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PRO_PHPV2> PRO_PHPV29 { get; set; }

}

}
