
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class Prorrogas
{

    public int prorroga_id { get; set; }

    public Nullable<int> paciente_id { get; set; }

    public Nullable<System.DateTime> fechaProrroga { get; set; }

    public Nullable<int> usuario_id { get; set; }

    public string antecedentes { get; set; }

    public string estadoAlIngreso { get; set; }

    public Nullable<bool> estadoProrroga { get; set; }

}

}
