//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Principal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SISTMEDEntities : DbContext
    {
        public SISTMEDEntities()
            : base("name=SISTMEDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Archivos_Paciente> Archivos_Paciente { get; set; }
        public virtual DbSet<ContactoPaciente> ContactoPaciente { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Enfermeria> Enfermeria { get; set; }
        public virtual DbSet<EST_LaboratorioCab> EST_LaboratorioCab { get; set; }
        public virtual DbSet<EST_LaboratorioDeterminaciones> EST_LaboratorioDeterminaciones { get; set; }
        public virtual DbSet<EST_LaboratorioEstados> EST_LaboratorioEstados { get; set; }
        public virtual DbSet<EST_LaboratorioItems> EST_LaboratorioItems { get; set; }
        public virtual DbSet<EST_LaboratorioTipoEstudio> EST_LaboratorioTipoEstudio { get; set; }
        public virtual DbSet<EST_LaboratorioTipos> EST_LaboratorioTipos { get; set; }
        public virtual DbSet<EstadosPertenenciasPaciente> EstadosPertenenciasPaciente { get; set; }
        public virtual DbSet<Farmacia> Farmacia { get; set; }
        public virtual DbSet<Habitaciones> Habitaciones { get; set; }
        public virtual DbSet<HC> HC { get; set; }
        public virtual DbSet<MED_Diagnostico> MED_Diagnostico { get; set; }
        public virtual DbSet<MED_Diagnostico_Paciente> MED_Diagnostico_Paciente { get; set; }
        public virtual DbSet<MED_Diagnosticos> MED_Diagnosticos { get; set; }
        public virtual DbSet<MED_Diluyente> MED_Diluyente { get; set; }
        public virtual DbSet<MED_Enfermeria> MED_Enfermeria { get; set; }
        public virtual DbSet<MED_Evento> MED_Evento { get; set; }
        public virtual DbSet<MED_Historial_SuministroDeMedicacion> MED_Historial_SuministroDeMedicacion { get; set; }
        public virtual DbSet<MED_HorarioDeSuministro> MED_HorarioDeSuministro { get; set; }
        public virtual DbSet<MED_ListaEsperaModulo> MED_ListaEsperaModulo { get; set; }
        public virtual DbSet<MED_Medicamento_Via> MED_Medicamento_Via { get; set; }
        public virtual DbSet<MED_Modulo> MED_Modulo { get; set; }
        public virtual DbSet<MED_ModuloEmpresa> MED_ModuloEmpresa { get; set; }
        public virtual DbSet<MED_Numero> MED_Numero { get; set; }
        public virtual DbSet<MED_OtraPonderacionPuntaje> MED_OtraPonderacionPuntaje { get; set; }
        public virtual DbSet<MED_PacienteModulo> MED_PacienteModulo { get; set; }
        public virtual DbSet<MED_PacienteModuloTesting> MED_PacienteModuloTesting { get; set; }
        public virtual DbSet<MED_Periodo> MED_Periodo { get; set; }
        public virtual DbSet<MED_Presentacion> MED_Presentacion { get; set; }
        public virtual DbSet<MED_SuministroDeMedicacion> MED_SuministroDeMedicacion { get; set; }
        public virtual DbSet<MED_UnidadDeMedida> MED_UnidadDeMedida { get; set; }
        public virtual DbSet<MED_Via> MED_Via { get; set; }
        public virtual DbSet<MotivoEgreso> MotivoEgreso { get; set; }
        public virtual DbSet<Pacientes_Historial> Pacientes_Historial { get; set; }
        public virtual DbSet<PertenenciasPaciente> PertenenciasPaciente { get; set; }
        public virtual DbSet<Piso> Piso { get; set; }
        public virtual DbSet<PRO_Aditivos> PRO_Aditivos { get; set; }
        public virtual DbSet<PRO_Alimento> PRO_Alimento { get; set; }
        public virtual DbSet<PRO_Asociacion_Procedimiento> PRO_Asociacion_Procedimiento { get; set; }
        public virtual DbSet<PRO_Colocacion_Via_Periferica> PRO_Colocacion_Via_Periferica { get; set; }
        public virtual DbSet<PRO_Cuidado_Oral> PRO_Cuidado_Oral { get; set; }
        public virtual DbSet<PRO_Cuidado_Postural> PRO_Cuidado_Postural { get; set; }
        public virtual DbSet<PRO_Enfermeria> PRO_Enfermeria { get; set; }
        public virtual DbSet<PRO_Frasco> PRO_Frasco { get; set; }
        public virtual DbSet<PRO_GavageIntervalo> PRO_GavageIntervalo { get; set; }
        public virtual DbSet<PRO_Generico> PRO_Generico { get; set; }
        public virtual DbSet<PRO_Gota_Hora> PRO_Gota_Hora { get; set; }
        public virtual DbSet<PRO_Historial_Colocacion_Via_Periferica> PRO_Historial_Colocacion_Via_Periferica { get; set; }
        public virtual DbSet<PRO_Historial_Cuidado_Oral> PRO_Historial_Cuidado_Oral { get; set; }
        public virtual DbSet<PRO_Historial_Cuidado_Postural> PRO_Historial_Cuidado_Postural { get; set; }
        public virtual DbSet<PRO_Historial_Enfermeria> PRO_Historial_Enfermeria { get; set; }
        public virtual DbSet<PRO_Historial_Generico> PRO_Historial_Generico { get; set; }
        public virtual DbSet<PRO_Historial_Php> PRO_Historial_Php { get; set; }
        public virtual DbSet<PRO_Historial_Posologia> PRO_Historial_Posologia { get; set; }
        public virtual DbSet<PRO_Historial_Proteccion_Fisica> PRO_Historial_Proteccion_Fisica { get; set; }
        public virtual DbSet<PRO_Historial_SuministroDeProcedimiento> PRO_Historial_SuministroDeProcedimiento { get; set; }
        public virtual DbSet<PRO_Php> PRO_Php { get; set; }
        public virtual DbSet<PRO_Preparado> PRO_Preparado { get; set; }
        public virtual DbSet<PRO_Procedimiento> PRO_Procedimiento { get; set; }
        public virtual DbSet<PRO_ProcedimientoDescartable> PRO_ProcedimientoDescartable { get; set; }
        public virtual DbSet<PRO_Proteccion_Fisica> PRO_Proteccion_Fisica { get; set; }
        public virtual DbSet<PRO_Tipo_Procedimiento> PRO_Tipo_Procedimiento { get; set; }
        public virtual DbSet<Prorrogas> Prorrogas { get; set; }
        public virtual DbSet<ProrrogasItem> ProrrogasItem { get; set; }
        public virtual DbSet<Regimenes> Regimenes { get; set; }
        public virtual DbSet<Sectores> Sectores { get; set; }
        public virtual DbSet<Sedes> Sedes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_Menus> TBL_Menus { get; set; }
        public virtual DbSet<TBL_Perfiles> TBL_Perfiles { get; set; }
        public virtual DbSet<TBL_PerfilesPermisos> TBL_PerfilesPermisos { get; set; }
        public virtual DbSet<TBL_Usuarios> TBL_Usuarios { get; set; }
        public virtual DbSet<TestPDF> TestPDF { get; set; }
        public virtual DbSet<Tipo_Archivo> Tipo_Archivo { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<MED_Via_Endovenosa> MED_Via_Endovenosa { get; set; }
        public virtual DbSet<PRO_Posologia> PRO_Posologia { get; set; }
        public virtual DbSet<PRO_PHPV2> PRO_PHPV2 { get; set; }
        public virtual DbSet<PRO_PHPV2_DILUYENTE> PRO_PHPV2_DILUYENTE { get; set; }
        public virtual DbSet<PRO_PHPV2_ADITIVO> PRO_PHPV2_ADITIVO { get; set; }
        public virtual DbSet<MED_PuntajeAdicionalListaEspera> MED_PuntajeAdicionalListaEspera { get; set; }
        public virtual DbSet<MED_Derivacion> MED_Derivacion { get; set; }
        public virtual DbSet<MED_CultivosListaEspera> MED_CultivosListaEspera { get; set; }
        public virtual DbSet<PacientesTesting> PacientesTesting { get; set; }
        public virtual DbSet<MED_ListaEspera> MED_ListaEspera { get; set; }
        public virtual DbSet<MED_Solicita_Medicamento_Nuevo> MED_Solicita_Medicamento_Nuevo { get; set; }
        public virtual DbSet<ARTICULO> ARTICULO { get; set; }
        public virtual DbSet<MEDICAMENTO> MEDICAMENTO { get; set; }
        public virtual DbSet<OBRA_SOCIAL> OBRA_SOCIAL { get; set; }
        public virtual DbSet<MED_TipoEgreso> MED_TipoEgreso { get; set; }
        public virtual DbSet<MED_Mails> MED_Mails { get; set; }
        public virtual DbSet<MED_SectorMails> MED_SectorMails { get; set; }
        public virtual DbSet<FARM_MOTIVO> FARM_MOTIVO { get; set; }
        public virtual DbSet<FARM_DIARIO> FARM_DIARIO { get; set; }
        public virtual DbSet<PRO_Asociacion_Procedimiento_Proc> PRO_Asociacion_Procedimiento_Proc { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<PRO_SuministroDeProcedimiento> PRO_SuministroDeProcedimiento { get; set; }
        public virtual DbSet<PRO_SuministroDeProcedimiento_Historico> PRO_SuministroDeProcedimiento_Historico { get; set; }
    
        [DbFunction("SISTMEDEntities", "TraeMedicamentosUnificado")]
        public virtual IQueryable<TraeMedicamentosUnificado_Result> TraeMedicamentosUnificado(Nullable<int> paciente_id)
        {
            var paciente_idParameter = paciente_id.HasValue ?
                new ObjectParameter("Paciente_id", paciente_id) :
                new ObjectParameter("Paciente_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TraeMedicamentosUnificado_Result>("[SISTMEDEntities].[TraeMedicamentosUnificado](@Paciente_id)", paciente_idParameter);
        }
    
        public virtual int ActualizaPuntajeObraSocial(string codEmp, string cli_Cod, Nullable<decimal> puntaje)
        {
            var codEmpParameter = codEmp != null ?
                new ObjectParameter("codEmp", codEmp) :
                new ObjectParameter("codEmp", typeof(string));
    
            var cli_CodParameter = cli_Cod != null ?
                new ObjectParameter("cli_Cod", cli_Cod) :
                new ObjectParameter("cli_Cod", typeof(string));
    
            var puntajeParameter = puntaje.HasValue ?
                new ObjectParameter("puntaje", puntaje) :
                new ObjectParameter("puntaje", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizaPuntajeObraSocial", codEmpParameter, cli_CodParameter, puntajeParameter);
        }
    
        public virtual ObjectResult<Get_Paciente_Por_Sede_Result> Get_Paciente_Por_Sede(Nullable<int> sEDE_ID, Nullable<int> pISO_ID)
        {
            var sEDE_IDParameter = sEDE_ID.HasValue ?
                new ObjectParameter("SEDE_ID", sEDE_ID) :
                new ObjectParameter("SEDE_ID", typeof(int));
    
            var pISO_IDParameter = pISO_ID.HasValue ?
                new ObjectParameter("PISO_ID", pISO_ID) :
                new ObjectParameter("PISO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Paciente_Por_Sede_Result>("Get_Paciente_Por_Sede", sEDE_IDParameter, pISO_IDParameter);
        }
    
        public virtual ObjectResult<Get_Piso_Por_Sede_Result> Get_Piso_Por_Sede(Nullable<int> sEDE_ID)
        {
            var sEDE_IDParameter = sEDE_ID.HasValue ?
                new ObjectParameter("SEDE_ID", sEDE_ID) :
                new ObjectParameter("SEDE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Piso_Por_Sede_Result>("Get_Piso_Por_Sede", sEDE_IDParameter);
        }
    
        public virtual int GrabaAltasDatatech(string sEDE)
        {
            var sEDEParameter = sEDE != null ?
                new ObjectParameter("SEDE", sEDE) :
                new ObjectParameter("SEDE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GrabaAltasDatatech", sEDEParameter);
        }
    
        public virtual ObjectResult<HC_TraeDatos_Result> HC_TraeDatos(Nullable<int> paciente_id, string tipo)
        {
            var paciente_idParameter = paciente_id.HasValue ?
                new ObjectParameter("Paciente_id", paciente_id) :
                new ObjectParameter("Paciente_id", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HC_TraeDatos_Result>("HC_TraeDatos", paciente_idParameter, tipoParameter);
        }
    
        public virtual int IMP_Epicrisis(Nullable<int> paciente_ID)
        {
            var paciente_IDParameter = paciente_ID.HasValue ?
                new ObjectParameter("Paciente_ID", paciente_ID) :
                new ObjectParameter("Paciente_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IMP_Epicrisis", paciente_IDParameter);
        }
    
        public virtual ObjectResult<IMP_HC_Result> IMP_HC(Nullable<int> paciente_id, string tipo, Nullable<System.DateTime> fechaDesde, Nullable<System.DateTime> fechaHasta)
        {
            var paciente_idParameter = paciente_id.HasValue ?
                new ObjectParameter("Paciente_id", paciente_id) :
                new ObjectParameter("Paciente_id", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var fechaDesdeParameter = fechaDesde.HasValue ?
                new ObjectParameter("FechaDesde", fechaDesde) :
                new ObjectParameter("FechaDesde", typeof(System.DateTime));
    
            var fechaHastaParameter = fechaHasta.HasValue ?
                new ObjectParameter("FechaHasta", fechaHasta) :
                new ObjectParameter("FechaHasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMP_HC_Result>("IMP_HC", paciente_idParameter, tipoParameter, fechaDesdeParameter, fechaHastaParameter);
        }
    
        public virtual ObjectResult<IMP_IM_Medicamentos_Result> IMP_IM_Medicamentos(Nullable<int> paciente_ID)
        {
            var paciente_IDParameter = paciente_ID.HasValue ?
                new ObjectParameter("Paciente_ID", paciente_ID) :
                new ObjectParameter("Paciente_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMP_IM_Medicamentos_Result>("IMP_IM_Medicamentos", paciente_IDParameter);
        }
    
        public virtual ObjectResult<IMP_IM_Procedimientos_Result> IMP_IM_Procedimientos(Nullable<int> paciente_ID)
        {
            var paciente_IDParameter = paciente_ID.HasValue ?
                new ObjectParameter("Paciente_ID", paciente_ID) :
                new ObjectParameter("Paciente_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMP_IM_Procedimientos_Result>("IMP_IM_Procedimientos", paciente_IDParameter);
        }
    
        public virtual int IMP_PedidoLaboratorios(string iNF, Nullable<System.DateTime> fECHA_DESDE, Nullable<System.DateTime> fECHA_HASTA, string sECTOR, Nullable<int> tIPO, Nullable<int> eSTADO)
        {
            var iNFParameter = iNF != null ?
                new ObjectParameter("INF", iNF) :
                new ObjectParameter("INF", typeof(string));
    
            var fECHA_DESDEParameter = fECHA_DESDE.HasValue ?
                new ObjectParameter("FECHA_DESDE", fECHA_DESDE) :
                new ObjectParameter("FECHA_DESDE", typeof(System.DateTime));
    
            var fECHA_HASTAParameter = fECHA_HASTA.HasValue ?
                new ObjectParameter("FECHA_HASTA", fECHA_HASTA) :
                new ObjectParameter("FECHA_HASTA", typeof(System.DateTime));
    
            var sECTORParameter = sECTOR != null ?
                new ObjectParameter("SECTOR", sECTOR) :
                new ObjectParameter("SECTOR", typeof(string));
    
            var tIPOParameter = tIPO.HasValue ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(int));
    
            var eSTADOParameter = eSTADO.HasValue ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IMP_PedidoLaboratorios", iNFParameter, fECHA_DESDEParameter, fECHA_HASTAParameter, sECTORParameter, tIPOParameter, eSTADOParameter);
        }
    
        public virtual ObjectResult<IMP_PRO_NUTRICION_Result> IMP_PRO_NUTRICION(Nullable<int> pACIENTE_ID)
        {
            var pACIENTE_IDParameter = pACIENTE_ID.HasValue ?
                new ObjectParameter("PACIENTE_ID", pACIENTE_ID) :
                new ObjectParameter("PACIENTE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMP_PRO_NUTRICION_Result>("IMP_PRO_NUTRICION", pACIENTE_IDParameter);
        }
    
        public virtual ObjectResult<IMP_PRO_PHP_Result> IMP_PRO_PHP(Nullable<int> pACIENTE_ID)
        {
            var pACIENTE_IDParameter = pACIENTE_ID.HasValue ?
                new ObjectParameter("PACIENTE_ID", pACIENTE_ID) :
                new ObjectParameter("PACIENTE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IMP_PRO_PHP_Result>("IMP_PRO_PHP", pACIENTE_IDParameter);
        }
    
        public virtual int IMP_Prorrogas(Nullable<int> paciente_id, string tipo, Nullable<System.DateTime> fechaDesde, Nullable<System.DateTime> fechaHasta)
        {
            var paciente_idParameter = paciente_id.HasValue ?
                new ObjectParameter("Paciente_id", paciente_id) :
                new ObjectParameter("Paciente_id", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            var fechaDesdeParameter = fechaDesde.HasValue ?
                new ObjectParameter("FechaDesde", fechaDesde) :
                new ObjectParameter("FechaDesde", typeof(System.DateTime));
    
            var fechaHastaParameter = fechaHasta.HasValue ?
                new ObjectParameter("FechaHasta", fechaHasta) :
                new ObjectParameter("FechaHasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IMP_Prorrogas", paciente_idParameter, tipoParameter, fechaDesdeParameter, fechaHastaParameter);
        }
    
        public virtual int MAP_Get_Horario_Medicamento(Nullable<int> pACIENTE_ID, string hS)
        {
            var pACIENTE_IDParameter = pACIENTE_ID.HasValue ?
                new ObjectParameter("PACIENTE_ID", pACIENTE_ID) :
                new ObjectParameter("PACIENTE_ID", typeof(int));
    
            var hSParameter = hS != null ?
                new ObjectParameter("HS", hS) :
                new ObjectParameter("HS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MAP_Get_Horario_Medicamento", pACIENTE_IDParameter, hSParameter);
        }
    
        public virtual ObjectResult<MED_Get_Diagnostico_Capitulo_Result> MED_Get_Diagnostico_Capitulo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_Get_Diagnostico_Capitulo_Result>("MED_Get_Diagnostico_Capitulo");
        }
    
        public virtual ObjectResult<MED_Get_Diagnostico_Item_Result> MED_Get_Diagnostico_Item(string cAPITULO_ID)
        {
            var cAPITULO_IDParameter = cAPITULO_ID != null ?
                new ObjectParameter("CAPITULO_ID", cAPITULO_ID) :
                new ObjectParameter("CAPITULO_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_Get_Diagnostico_Item_Result>("MED_Get_Diagnostico_Item", cAPITULO_IDParameter);
        }
    
        public virtual ObjectResult<MED_Get_Diagnostico_Paciente_Result> MED_Get_Diagnostico_Paciente(Nullable<int> pACIENTE_ID)
        {
            var pACIENTE_IDParameter = pACIENTE_ID.HasValue ?
                new ObjectParameter("PACIENTE_ID", pACIENTE_ID) :
                new ObjectParameter("PACIENTE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_Get_Diagnostico_Paciente_Result>("MED_Get_Diagnostico_Paciente", pACIENTE_IDParameter);
        }
    
        public virtual ObjectResult<MED_Get_Diagnostico_Rubro_Result> MED_Get_Diagnostico_Rubro(string gRUPO_ID)
        {
            var gRUPO_IDParameter = gRUPO_ID != null ?
                new ObjectParameter("GRUPO_ID", gRUPO_ID) :
                new ObjectParameter("GRUPO_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_Get_Diagnostico_Rubro_Result>("MED_Get_Diagnostico_Rubro", gRUPO_IDParameter);
        }
    
        public virtual ObjectResult<MED_Get_Diagnostico_SubRubro_Result> MED_Get_Diagnostico_SubRubro(string gRUPO_ID)
        {
            var gRUPO_IDParameter = gRUPO_ID != null ?
                new ObjectParameter("GRUPO_ID", gRUPO_ID) :
                new ObjectParameter("GRUPO_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_Get_Diagnostico_SubRubro_Result>("MED_Get_Diagnostico_SubRubro", gRUPO_IDParameter);
        }
    
        public virtual ObjectResult<MED_Get_Horarios_Paciente_Result> MED_Get_Horarios_Paciente(Nullable<int> pACIENTE_ID)
        {
            var pACIENTE_IDParameter = pACIENTE_ID.HasValue ?
                new ObjectParameter("PACIENTE_ID", pACIENTE_ID) :
                new ObjectParameter("PACIENTE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_Get_Horarios_Paciente_Result>("MED_Get_Horarios_Paciente", pACIENTE_IDParameter);
        }
    
        public virtual ObjectResult<MED_Get_Medicamento_Bejerman_Result> MED_Get_Medicamento_Bejerman(string mEDICAMENTO_ID)
        {
            var mEDICAMENTO_IDParameter = mEDICAMENTO_ID != null ?
                new ObjectParameter("MEDICAMENTO_ID", mEDICAMENTO_ID) :
                new ObjectParameter("MEDICAMENTO_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_Get_Medicamento_Bejerman_Result>("MED_Get_Medicamento_Bejerman", mEDICAMENTO_IDParameter);
        }
    
        public virtual ObjectResult<MED_Get_Medicamento_Indicacion_Medica_Result> MED_Get_Medicamento_Indicacion_Medica(string mEDICAMENTO_ID, Nullable<bool> iNACTIVO)
        {
            var mEDICAMENTO_IDParameter = mEDICAMENTO_ID != null ?
                new ObjectParameter("MEDICAMENTO_ID", mEDICAMENTO_ID) :
                new ObjectParameter("MEDICAMENTO_ID", typeof(string));
    
            var iNACTIVOParameter = iNACTIVO.HasValue ?
                new ObjectParameter("INACTIVO", iNACTIVO) :
                new ObjectParameter("INACTIVO", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_Get_Medicamento_Indicacion_Medica_Result>("MED_Get_Medicamento_Indicacion_Medica", mEDICAMENTO_IDParameter, iNACTIVOParameter);
        }
    
        public virtual ObjectResult<MED_Get_Medicamento_Solicitado_Result> MED_Get_Medicamento_Solicitado(Nullable<bool> aUTORIZA, Nullable<bool> pENDIENTE)
        {
            var aUTORIZAParameter = aUTORIZA.HasValue ?
                new ObjectParameter("AUTORIZA", aUTORIZA) :
                new ObjectParameter("AUTORIZA", typeof(bool));
    
            var pENDIENTEParameter = pENDIENTE.HasValue ?
                new ObjectParameter("PENDIENTE", pENDIENTE) :
                new ObjectParameter("PENDIENTE", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_Get_Medicamento_Solicitado_Result>("MED_Get_Medicamento_Solicitado", aUTORIZAParameter, pENDIENTEParameter);
        }
    
        public virtual ObjectResult<MED_Get_Medicamento_Via_Result> MED_Get_Medicamento_Via(string mEDICAMENTO_ID, Nullable<bool> iNACTIVO)
        {
            var mEDICAMENTO_IDParameter = mEDICAMENTO_ID != null ?
                new ObjectParameter("MEDICAMENTO_ID", mEDICAMENTO_ID) :
                new ObjectParameter("MEDICAMENTO_ID", typeof(string));
    
            var iNACTIVOParameter = iNACTIVO.HasValue ?
                new ObjectParameter("INACTIVO", iNACTIVO) :
                new ObjectParameter("INACTIVO", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_Get_Medicamento_Via_Result>("MED_Get_Medicamento_Via", mEDICAMENTO_IDParameter, iNACTIVOParameter);
        }
    
        public virtual ObjectResult<MED_Get_Suministro_Medicacion_Result> MED_Get_Suministro_Medicacion(Nullable<int> sUMINISTRO_MEDICACION_ID, Nullable<int> pACIENTE_ID, string mEDICAMENTO_ID, string tIPOGET)
        {
            var sUMINISTRO_MEDICACION_IDParameter = sUMINISTRO_MEDICACION_ID.HasValue ?
                new ObjectParameter("SUMINISTRO_MEDICACION_ID", sUMINISTRO_MEDICACION_ID) :
                new ObjectParameter("SUMINISTRO_MEDICACION_ID", typeof(int));
    
            var pACIENTE_IDParameter = pACIENTE_ID.HasValue ?
                new ObjectParameter("PACIENTE_ID", pACIENTE_ID) :
                new ObjectParameter("PACIENTE_ID", typeof(int));
    
            var mEDICAMENTO_IDParameter = mEDICAMENTO_ID != null ?
                new ObjectParameter("MEDICAMENTO_ID", mEDICAMENTO_ID) :
                new ObjectParameter("MEDICAMENTO_ID", typeof(string));
    
            var tIPOGETParameter = tIPOGET != null ?
                new ObjectParameter("TIPOGET", tIPOGET) :
                new ObjectParameter("TIPOGET", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_Get_Suministro_Medicacion_Result>("MED_Get_Suministro_Medicacion", sUMINISTRO_MEDICACION_IDParameter, pACIENTE_IDParameter, mEDICAMENTO_IDParameter, tIPOGETParameter);
        }
    
        public virtual ObjectResult<MED_Get_Via_Result> MED_Get_Via(string iNACTIVO)
        {
            var iNACTIVOParameter = iNACTIVO != null ?
                new ObjectParameter("INACTIVO", iNACTIVO) :
                new ObjectParameter("INACTIVO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_Get_Via_Result>("MED_Get_Via", iNACTIVOParameter);
        }
    
        public virtual int MED_Report_Get_Suministro_Medicacion(Nullable<int> pACIENTE_ID, string tipoInf)
        {
            var pACIENTE_IDParameter = pACIENTE_ID.HasValue ?
                new ObjectParameter("PACIENTE_ID", pACIENTE_ID) :
                new ObjectParameter("PACIENTE_ID", typeof(int));
    
            var tipoInfParameter = tipoInf != null ?
                new ObjectParameter("TipoInf", tipoInf) :
                new ObjectParameter("TipoInf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MED_Report_Get_Suministro_Medicacion", pACIENTE_IDParameter, tipoInfParameter);
        }
    
        public virtual ObjectResult<MED_TraeModuloEmpresaCosto_Result> MED_TraeModuloEmpresaCosto(string codEmp)
        {
            var codEmpParameter = codEmp != null ?
                new ObjectParameter("codEmp", codEmp) :
                new ObjectParameter("codEmp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_TraeModuloEmpresaCosto_Result>("MED_TraeModuloEmpresaCosto", codEmpParameter);
        }
    
        public virtual int MED_Up_Horarios_Paciente(Nullable<int> pACIENTE_ID, Nullable<int> hS_08, Nullable<int> hS_09, Nullable<int> hS_10, Nullable<int> hS_11, Nullable<int> hS_12, Nullable<int> hS_13, Nullable<int> hS_14, Nullable<int> hS_15, Nullable<int> hS_16, Nullable<int> hS_17, Nullable<int> hS_18, Nullable<int> hS_19, Nullable<int> hS_20, Nullable<int> hS_21, Nullable<int> hS_22, Nullable<int> hS_23, Nullable<int> hS_24, Nullable<int> hS_01, Nullable<int> hS_02, Nullable<int> hS_03, Nullable<int> hS_04, Nullable<int> hS_05, Nullable<int> hS_06, Nullable<int> hS_07, Nullable<int> hS_SH)
        {
            var pACIENTE_IDParameter = pACIENTE_ID.HasValue ?
                new ObjectParameter("PACIENTE_ID", pACIENTE_ID) :
                new ObjectParameter("PACIENTE_ID", typeof(int));
    
            var hS_08Parameter = hS_08.HasValue ?
                new ObjectParameter("HS_08", hS_08) :
                new ObjectParameter("HS_08", typeof(int));
    
            var hS_09Parameter = hS_09.HasValue ?
                new ObjectParameter("HS_09", hS_09) :
                new ObjectParameter("HS_09", typeof(int));
    
            var hS_10Parameter = hS_10.HasValue ?
                new ObjectParameter("HS_10", hS_10) :
                new ObjectParameter("HS_10", typeof(int));
    
            var hS_11Parameter = hS_11.HasValue ?
                new ObjectParameter("HS_11", hS_11) :
                new ObjectParameter("HS_11", typeof(int));
    
            var hS_12Parameter = hS_12.HasValue ?
                new ObjectParameter("HS_12", hS_12) :
                new ObjectParameter("HS_12", typeof(int));
    
            var hS_13Parameter = hS_13.HasValue ?
                new ObjectParameter("HS_13", hS_13) :
                new ObjectParameter("HS_13", typeof(int));
    
            var hS_14Parameter = hS_14.HasValue ?
                new ObjectParameter("HS_14", hS_14) :
                new ObjectParameter("HS_14", typeof(int));
    
            var hS_15Parameter = hS_15.HasValue ?
                new ObjectParameter("HS_15", hS_15) :
                new ObjectParameter("HS_15", typeof(int));
    
            var hS_16Parameter = hS_16.HasValue ?
                new ObjectParameter("HS_16", hS_16) :
                new ObjectParameter("HS_16", typeof(int));
    
            var hS_17Parameter = hS_17.HasValue ?
                new ObjectParameter("HS_17", hS_17) :
                new ObjectParameter("HS_17", typeof(int));
    
            var hS_18Parameter = hS_18.HasValue ?
                new ObjectParameter("HS_18", hS_18) :
                new ObjectParameter("HS_18", typeof(int));
    
            var hS_19Parameter = hS_19.HasValue ?
                new ObjectParameter("HS_19", hS_19) :
                new ObjectParameter("HS_19", typeof(int));
    
            var hS_20Parameter = hS_20.HasValue ?
                new ObjectParameter("HS_20", hS_20) :
                new ObjectParameter("HS_20", typeof(int));
    
            var hS_21Parameter = hS_21.HasValue ?
                new ObjectParameter("HS_21", hS_21) :
                new ObjectParameter("HS_21", typeof(int));
    
            var hS_22Parameter = hS_22.HasValue ?
                new ObjectParameter("HS_22", hS_22) :
                new ObjectParameter("HS_22", typeof(int));
    
            var hS_23Parameter = hS_23.HasValue ?
                new ObjectParameter("HS_23", hS_23) :
                new ObjectParameter("HS_23", typeof(int));
    
            var hS_24Parameter = hS_24.HasValue ?
                new ObjectParameter("HS_24", hS_24) :
                new ObjectParameter("HS_24", typeof(int));
    
            var hS_01Parameter = hS_01.HasValue ?
                new ObjectParameter("HS_01", hS_01) :
                new ObjectParameter("HS_01", typeof(int));
    
            var hS_02Parameter = hS_02.HasValue ?
                new ObjectParameter("HS_02", hS_02) :
                new ObjectParameter("HS_02", typeof(int));
    
            var hS_03Parameter = hS_03.HasValue ?
                new ObjectParameter("HS_03", hS_03) :
                new ObjectParameter("HS_03", typeof(int));
    
            var hS_04Parameter = hS_04.HasValue ?
                new ObjectParameter("HS_04", hS_04) :
                new ObjectParameter("HS_04", typeof(int));
    
            var hS_05Parameter = hS_05.HasValue ?
                new ObjectParameter("HS_05", hS_05) :
                new ObjectParameter("HS_05", typeof(int));
    
            var hS_06Parameter = hS_06.HasValue ?
                new ObjectParameter("HS_06", hS_06) :
                new ObjectParameter("HS_06", typeof(int));
    
            var hS_07Parameter = hS_07.HasValue ?
                new ObjectParameter("HS_07", hS_07) :
                new ObjectParameter("HS_07", typeof(int));
    
            var hS_SHParameter = hS_SH.HasValue ?
                new ObjectParameter("HS_SH", hS_SH) :
                new ObjectParameter("HS_SH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MED_Up_Horarios_Paciente", pACIENTE_IDParameter, hS_08Parameter, hS_09Parameter, hS_10Parameter, hS_11Parameter, hS_12Parameter, hS_13Parameter, hS_14Parameter, hS_15Parameter, hS_16Parameter, hS_17Parameter, hS_18Parameter, hS_19Parameter, hS_20Parameter, hS_21Parameter, hS_22Parameter, hS_23Parameter, hS_24Parameter, hS_01Parameter, hS_02Parameter, hS_03Parameter, hS_04Parameter, hS_05Parameter, hS_06Parameter, hS_07Parameter, hS_SHParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ObtieneUltimaHistoriaClinica(Nullable<int> eMPRESA_ID)
        {
            var eMPRESA_IDParameter = eMPRESA_ID.HasValue ?
                new ObjectParameter("EMPRESA_ID", eMPRESA_ID) :
                new ObjectParameter("EMPRESA_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ObtieneUltimaHistoriaClinica", eMPRESA_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> ObtieneUltimoId(string tABLA)
        {
            var tABLAParameter = tABLA != null ?
                new ObjectParameter("TABLA", tABLA) :
                new ObjectParameter("TABLA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("ObtieneUltimoId", tABLAParameter);
        }
    
        public virtual ObjectResult<PRO_Get_Abocath_Numero_Result> PRO_Get_Abocath_Numero()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_Abocath_Numero_Result>("PRO_Get_Abocath_Numero");
        }
    
        public virtual ObjectResult<PRO_Get_Colocacion_Via_Periferica_Result> PRO_Get_Colocacion_Via_Periferica(Nullable<int> cOLOCACION_VIA_PERIFERICA_ID)
        {
            var cOLOCACION_VIA_PERIFERICA_IDParameter = cOLOCACION_VIA_PERIFERICA_ID.HasValue ?
                new ObjectParameter("COLOCACION_VIA_PERIFERICA_ID", cOLOCACION_VIA_PERIFERICA_ID) :
                new ObjectParameter("COLOCACION_VIA_PERIFERICA_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_Colocacion_Via_Periferica_Result>("PRO_Get_Colocacion_Via_Periferica", cOLOCACION_VIA_PERIFERICA_IDParameter);
        }
    
        public virtual ObjectResult<PRO_Get_Cuidado_Oral_Result> PRO_Get_Cuidado_Oral(Nullable<int> cUIDADO_ORAL_ID)
        {
            var cUIDADO_ORAL_IDParameter = cUIDADO_ORAL_ID.HasValue ?
                new ObjectParameter("CUIDADO_ORAL_ID", cUIDADO_ORAL_ID) :
                new ObjectParameter("CUIDADO_ORAL_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_Cuidado_Oral_Result>("PRO_Get_Cuidado_Oral", cUIDADO_ORAL_IDParameter);
        }
    
        public virtual ObjectResult<PRO_Get_Cuidado_Postural_Result> PRO_Get_Cuidado_Postural(Nullable<int> cUIDADO_POSTURAL_ID)
        {
            var cUIDADO_POSTURAL_IDParameter = cUIDADO_POSTURAL_ID.HasValue ?
                new ObjectParameter("CUIDADO_POSTURAL_ID", cUIDADO_POSTURAL_ID) :
                new ObjectParameter("CUIDADO_POSTURAL_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_Cuidado_Postural_Result>("PRO_Get_Cuidado_Postural", cUIDADO_POSTURAL_IDParameter);
        }
    
        public virtual ObjectResult<PRO_Get_Enfermeria_Result> PRO_Get_Enfermeria(Nullable<int> eNFERMERIA_ID)
        {
            var eNFERMERIA_IDParameter = eNFERMERIA_ID.HasValue ?
                new ObjectParameter("ENFERMERIA_ID", eNFERMERIA_ID) :
                new ObjectParameter("ENFERMERIA_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_Enfermeria_Result>("PRO_Get_Enfermeria", eNFERMERIA_IDParameter);
        }
    
        public virtual ObjectResult<PRO_Get_Generico_Result> PRO_Get_Generico(Nullable<int> gENERICO_ID)
        {
            var gENERICO_IDParameter = gENERICO_ID.HasValue ?
                new ObjectParameter("GENERICO_ID", gENERICO_ID) :
                new ObjectParameter("GENERICO_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_Generico_Result>("PRO_Get_Generico", gENERICO_IDParameter);
        }
    
        public virtual ObjectResult<PRO_Get_Php_Result> PRO_Get_Php(Nullable<int> pHP_ID)
        {
            var pHP_IDParameter = pHP_ID.HasValue ?
                new ObjectParameter("PHP_ID", pHP_ID) :
                new ObjectParameter("PHP_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_Php_Result>("PRO_Get_Php", pHP_IDParameter);
        }
    
        public virtual ObjectResult<PRO_Get_Php_Aditivo_Result> PRO_Get_Php_Aditivo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_Php_Aditivo_Result>("PRO_Get_Php_Aditivo");
        }
    
        public virtual ObjectResult<PRO_Get_Posologia_Result> PRO_Get_Posologia(Nullable<int> pOSOLOGIA_ID)
        {
            var pOSOLOGIA_IDParameter = pOSOLOGIA_ID.HasValue ?
                new ObjectParameter("POSOLOGIA_ID", pOSOLOGIA_ID) :
                new ObjectParameter("POSOLOGIA_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_Posologia_Result>("PRO_Get_Posologia", pOSOLOGIA_IDParameter);
        }
    
        public virtual ObjectResult<PRO_Get_Procedimiento_Result> PRO_Get_Procedimiento(string pROCEDIMIENTO)
        {
            var pROCEDIMIENTOParameter = pROCEDIMIENTO != null ?
                new ObjectParameter("PROCEDIMIENTO", pROCEDIMIENTO) :
                new ObjectParameter("PROCEDIMIENTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_Procedimiento_Result>("PRO_Get_Procedimiento", pROCEDIMIENTOParameter);
        }
    
        public virtual ObjectResult<PRO_Get_Procedimiento_Paciente_Result> PRO_Get_Procedimiento_Paciente(Nullable<int> pACIENTE_ID)
        {
            var pACIENTE_IDParameter = pACIENTE_ID.HasValue ?
                new ObjectParameter("PACIENTE_ID", pACIENTE_ID) :
                new ObjectParameter("PACIENTE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_Procedimiento_Paciente_Result>("PRO_Get_Procedimiento_Paciente", pACIENTE_IDParameter);
        }
    
        public virtual ObjectResult<PRO_Get_ProcedimientoTodos_Result> PRO_Get_ProcedimientoTodos(string pROCEDIMIENTO)
        {
            var pROCEDIMIENTOParameter = pROCEDIMIENTO != null ?
                new ObjectParameter("PROCEDIMIENTO", pROCEDIMIENTO) :
                new ObjectParameter("PROCEDIMIENTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_ProcedimientoTodos_Result>("PRO_Get_ProcedimientoTodos", pROCEDIMIENTOParameter);
        }
    
        public virtual ObjectResult<PRO_Get_Proteccion_Fisica_Result> PRO_Get_Proteccion_Fisica(Nullable<int> pROTECCION_FISICA_ID)
        {
            var pROTECCION_FISICA_IDParameter = pROTECCION_FISICA_ID.HasValue ?
                new ObjectParameter("PROTECCION_FISICA_ID", pROTECCION_FISICA_ID) :
                new ObjectParameter("PROTECCION_FISICA_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_Get_Proteccion_Fisica_Result>("PRO_Get_Proteccion_Fisica", pROTECCION_FISICA_IDParameter);
        }
    
        public virtual ObjectResult<PRO_TRAE_MEDICACION_PROCEDIMIENTO_Result> PRO_TRAE_MEDICACION_PROCEDIMIENTO(Nullable<int> suministro_id)
        {
            var suministro_idParameter = suministro_id.HasValue ?
                new ObjectParameter("Suministro_id", suministro_id) :
                new ObjectParameter("Suministro_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRO_TRAE_MEDICACION_PROCEDIMIENTO_Result>("PRO_TRAE_MEDICACION_PROCEDIMIENTO", suministro_idParameter);
        }
    
        public virtual ObjectResult<ProrrogasUltimaModificacion_Result> ProrrogasUltimaModificacion(Nullable<int> prorroga_id, string tipo)
        {
            var prorroga_idParameter = prorroga_id.HasValue ?
                new ObjectParameter("prorroga_id", prorroga_id) :
                new ObjectParameter("prorroga_id", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProrrogasUltimaModificacion_Result>("ProrrogasUltimaModificacion", prorroga_idParameter, tipoParameter);
        }
    
        public virtual ObjectResult<ProrrogaUltimoDetalle_Result> ProrrogaUltimoDetalle(Nullable<int> id_Prorroga)
        {
            var id_ProrrogaParameter = id_Prorroga.HasValue ?
                new ObjectParameter("Id_Prorroga", id_Prorroga) :
                new ObjectParameter("Id_Prorroga", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProrrogaUltimoDetalle_Result>("ProrrogaUltimoDetalle", id_ProrrogaParameter);
        }
    
        public virtual ObjectResult<PuntajeObraSocial_Result> PuntajeObraSocial(string codEmp)
        {
            var codEmpParameter = codEmp != null ?
                new ObjectParameter("codEmp", codEmp) :
                new ObjectParameter("codEmp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PuntajeObraSocial_Result>("PuntajeObraSocial", codEmpParameter);
        }
    
        public virtual int TRAECABECERANUTRICION(Nullable<int> paciente)
        {
            var pacienteParameter = paciente.HasValue ?
                new ObjectParameter("Paciente", paciente) :
                new ObjectParameter("Paciente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TRAECABECERANUTRICION", pacienteParameter);
        }
    
        public virtual ObjectResult<TraeCantidadLlamadosPaciente_Result> TraeCantidadLlamadosPaciente(Nullable<int> paciente)
        {
            var pacienteParameter = paciente.HasValue ?
                new ObjectParameter("Paciente", paciente) :
                new ObjectParameter("Paciente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraeCantidadLlamadosPaciente_Result>("TraeCantidadLlamadosPaciente", pacienteParameter);
        }
    
        public virtual ObjectResult<TRAECONTACTOPACIENTE_Result> TRAECONTACTOPACIENTE(Nullable<int> paciente)
        {
            var pacienteParameter = paciente.HasValue ?
                new ObjectParameter("paciente", paciente) :
                new ObjectParameter("paciente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TRAECONTACTOPACIENTE_Result>("TRAECONTACTOPACIENTE", pacienteParameter);
        }
    
        public virtual ObjectResult<TraeContactosPaciente_Result> TraeContactosPaciente(Nullable<int> paciente)
        {
            var pacienteParameter = paciente.HasValue ?
                new ObjectParameter("Paciente", paciente) :
                new ObjectParameter("Paciente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraeContactosPaciente_Result>("TraeContactosPaciente", pacienteParameter);
        }
    
        public virtual ObjectResult<TRAEDESCARTABLES_Result> TRAEDESCARTABLES(string descartable)
        {
            var descartableParameter = descartable != null ?
                new ObjectParameter("Descartable", descartable) :
                new ObjectParameter("Descartable", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TRAEDESCARTABLES_Result>("TRAEDESCARTABLES", descartableParameter);
        }
    
        public virtual ObjectResult<TRAEDESCARTABLESPROCEDIMIENTO_Result> TRAEDESCARTABLESPROCEDIMIENTO(Nullable<int> procedimiento)
        {
            var procedimientoParameter = procedimiento.HasValue ?
                new ObjectParameter("Procedimiento", procedimiento) :
                new ObjectParameter("Procedimiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TRAEDESCARTABLESPROCEDIMIENTO_Result>("TRAEDESCARTABLESPROCEDIMIENTO", procedimientoParameter);
        }
    
        public virtual ObjectResult<TRAEENTERALES_Result> TRAEENTERALES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TRAEENTERALES_Result>("TRAEENTERALES");
        }
    
        public virtual ObjectResult<TraeHabitacionesLibres_Result> TraeHabitacionesLibres(Nullable<int> sede, Nullable<int> actualiza, Nullable<int> habID)
        {
            var sedeParameter = sede.HasValue ?
                new ObjectParameter("Sede", sede) :
                new ObjectParameter("Sede", typeof(int));
    
            var actualizaParameter = actualiza.HasValue ?
                new ObjectParameter("Actualiza", actualiza) :
                new ObjectParameter("Actualiza", typeof(int));
    
            var habIDParameter = habID.HasValue ?
                new ObjectParameter("HabID", habID) :
                new ObjectParameter("HabID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraeHabitacionesLibres_Result>("TraeHabitacionesLibres", sedeParameter, actualizaParameter, habIDParameter);
        }
    
        public virtual int TRAEINDICACIONPROCEDIMIENTO(Nullable<int> paciente_id, Nullable<int> procedimiento_id)
        {
            var paciente_idParameter = paciente_id.HasValue ?
                new ObjectParameter("paciente_id", paciente_id) :
                new ObjectParameter("paciente_id", typeof(int));
    
            var procedimiento_idParameter = procedimiento_id.HasValue ?
                new ObjectParameter("procedimiento_id", procedimiento_id) :
                new ObjectParameter("procedimiento_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TRAEINDICACIONPROCEDIMIENTO", paciente_idParameter, procedimiento_idParameter);
        }
    
        public virtual int TRAEMEDICACIONPACIENTE(Nullable<int> paciente)
        {
            var pacienteParameter = paciente.HasValue ?
                new ObjectParameter("Paciente", paciente) :
                new ObjectParameter("Paciente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TRAEMEDICACIONPACIENTE", pacienteParameter);
        }
    
        public virtual ObjectResult<TRAEMEDICAMENTOS_Result> TRAEMEDICAMENTOS(string medicamento_id)
        {
            var medicamento_idParameter = medicamento_id != null ?
                new ObjectParameter("Medicamento_id", medicamento_id) :
                new ObjectParameter("Medicamento_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TRAEMEDICAMENTOS_Result>("TRAEMEDICAMENTOS", medicamento_idParameter);
        }
    
        public virtual int TRAENUTRICIONPACIENTE(Nullable<int> paciente)
        {
            var pacienteParameter = paciente.HasValue ?
                new ObjectParameter("Paciente", paciente) :
                new ObjectParameter("Paciente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TRAENUTRICIONPACIENTE", pacienteParameter);
        }
    
        public virtual ObjectResult<TraeObrasSociales_Result> TraeObrasSociales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraeObrasSociales_Result>("TraeObrasSociales");
        }
    
        public virtual ObjectResult<TraePacientesDeAlta_Result> TraePacientesDeAlta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraePacientesDeAlta_Result>("TraePacientesDeAlta");
        }
    
        public virtual ObjectResult<TraePacientesPertenecia_Result> TraePacientesPertenecia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraePacientesPertenecia_Result>("TraePacientesPertenecia");
        }
    
        public virtual ObjectResult<Nullable<int>> ULTIMA_POSICION_MENU(Nullable<int> menuaPadre)
        {
            var menuaPadreParameter = menuaPadre.HasValue ?
                new ObjectParameter("MenuaPadre", menuaPadre) :
                new ObjectParameter("MenuaPadre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ULTIMA_POSICION_MENU", menuaPadreParameter);
        }
    
        public virtual int UpdateFechaBajaPaciente(Nullable<System.DateTime> fEgreso, Nullable<int> paciente_id)
        {
            var fEgresoParameter = fEgreso.HasValue ?
                new ObjectParameter("fEgreso", fEgreso) :
                new ObjectParameter("fEgreso", typeof(System.DateTime));
    
            var paciente_idParameter = paciente_id.HasValue ?
                new ObjectParameter("paciente_id", paciente_id) :
                new ObjectParameter("paciente_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateFechaBajaPaciente", fEgresoParameter, paciente_idParameter);
        }
    
        public virtual int EnviaMailNuevoIngreso(Nullable<int> espera_id, string obs, Nullable<int> sectorMail, string adjuntos)
        {
            var espera_idParameter = espera_id.HasValue ?
                new ObjectParameter("espera_id", espera_id) :
                new ObjectParameter("espera_id", typeof(int));
    
            var obsParameter = obs != null ?
                new ObjectParameter("Obs", obs) :
                new ObjectParameter("Obs", typeof(string));
    
            var sectorMailParameter = sectorMail.HasValue ?
                new ObjectParameter("sectorMail", sectorMail) :
                new ObjectParameter("sectorMail", typeof(int));
    
            var adjuntosParameter = adjuntos != null ?
                new ObjectParameter("adjuntos", adjuntos) :
                new ObjectParameter("adjuntos", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EnviaMailNuevoIngreso", espera_idParameter, obsParameter, sectorMailParameter, adjuntosParameter);
        }
    
        public virtual ObjectResult<TraeListaEspera_Result> TraeListaEspera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraeListaEspera_Result>("TraeListaEspera");
        }
    
        public virtual ObjectResult<TraeVisorListaEspera_Result> TraeVisorListaEspera()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraeVisorListaEspera_Result>("TraeVisorListaEspera");
        }
    
        public virtual ObjectResult<TraeVisorListaEsperaEliminados_Result> TraeVisorListaEsperaEliminados(Nullable<System.DateTime> fechaDesde, Nullable<System.DateTime> fechaHasta)
        {
            var fechaDesdeParameter = fechaDesde.HasValue ?
                new ObjectParameter("FechaDesde", fechaDesde) :
                new ObjectParameter("FechaDesde", typeof(System.DateTime));
    
            var fechaHastaParameter = fechaHasta.HasValue ?
                new ObjectParameter("FechaHasta", fechaHasta) :
                new ObjectParameter("FechaHasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraeVisorListaEsperaEliminados_Result>("TraeVisorListaEsperaEliminados", fechaDesdeParameter, fechaHastaParameter);
        }
    
        public virtual ObjectResult<MED_GET_Suministro_Medicacion_Historico_Result> MED_GET_Suministro_Medicacion_Historico(Nullable<int> pACIENTE_ID)
        {
            var pACIENTE_IDParameter = pACIENTE_ID.HasValue ?
                new ObjectParameter("PACIENTE_ID", pACIENTE_ID) :
                new ObjectParameter("PACIENTE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MED_GET_Suministro_Medicacion_Historico_Result>("MED_GET_Suministro_Medicacion_Historico", pACIENTE_IDParameter);
        }
    
        public virtual int MED_ActualizaMotivoEgreso(Nullable<int> motivoEgreso_id, string descripcion, Nullable<int> idTipo)
        {
            var motivoEgreso_idParameter = motivoEgreso_id.HasValue ?
                new ObjectParameter("motivoEgreso_id", motivoEgreso_id) :
                new ObjectParameter("motivoEgreso_id", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("idTipo", idTipo) :
                new ObjectParameter("idTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MED_ActualizaMotivoEgreso", motivoEgreso_idParameter, descripcionParameter, idTipoParameter);
        }
    
        public virtual int MED_ingresoSectorMail(Nullable<int> sede_id, string descripcion)
        {
            var sede_idParameter = sede_id.HasValue ?
                new ObjectParameter("sede_id", sede_id) :
                new ObjectParameter("sede_id", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MED_ingresoSectorMail", sede_idParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<Get_Paciente_Result> Get_Paciente(Nullable<int> pACIENTE_ID)
        {
            var pACIENTE_IDParameter = pACIENTE_ID.HasValue ?
                new ObjectParameter("PACIENTE_ID", pACIENTE_ID) :
                new ObjectParameter("PACIENTE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Paciente_Result>("Get_Paciente", pACIENTE_IDParameter);
        }
    }
}
