
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_Perfiles
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TBL_Perfiles()
    {

        this.TBL_PerfilesPermisos = new HashSet<TBL_PerfilesPermisos>();

        this.TBL_Usuarios = new HashSet<TBL_Usuarios>();

    }


    public int Id_Perfil { get; set; }

    public string NombrePerfil { get; set; }

    public string DescripcionPerfil { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TBL_PerfilesPermisos> TBL_PerfilesPermisos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TBL_Usuarios> TBL_Usuarios { get; set; }

}

}
