
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Principal
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_PerfilesPermisos
{

    public int Id_PerfilPermisos { get; set; }

    public int Id_Perfil { get; set; }

    public int Id_Menu { get; set; }

    public bool Lectura { get; set; }

    public bool Escritura { get; set; }

    public bool Eliminacion { get; set; }



    public virtual TBL_Menus TBL_Menus { get; set; }

    public virtual TBL_Perfiles TBL_Perfiles { get; set; }

}

}
